"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.statusCodes = void 0;
var statusCodes = {
  // Successful Status Codes
  SUCCESSFUL_OK: 0x0000,
  SUCCESSFUL_OK_IGNORED_OR_SUBSTITUTED_ATTRIBUTES: 0x0001,
  SUCCESSFUL_OK_CONFLICTING_ATTRIBUTES: 0x0002,
  // Client Error Status Codes
  CLIENT_ERROR_BAD_REQUEST: 0x0400,
  CLIENT_ERROR_FORBIDDEN: 0x0401,
  CLIENT_ERROR_NOT_AUTHENTICATED: 0x0402,
  CLIENT_ERROR_NOT_AUTHORIZED: 0x0403,
  CLIENT_ERROR_NOT_POSSIBLE: 0x0404,
  CLIENT_ERROR_TIMEOUT: 0x0405,
  CLIENT_ERROR_NOT_FOUND: 0x0406,
  CLIENT_ERROR_GONE: 0x0407,
  CLIENT_ERROR_REQUEST_ENTITY_TOO_LARGE: 0x0408,
  CLIENT_ERROR_REQUEST_VALUE_TOO_LONG: 0x0409,
  CLIENT_ERROR_DOCUMENT_FORMAT_NOT_SUPPORTED: 0x040a,
  CLIENT_ERROR_ATTRIBUTES_OR_VALUES_NOT_SUPPORTED: 0x040b,
  CLIENT_ERROR_URI_SCHEME_NOT_SUPPORTED: 0x040c,
  CLIENT_ERROR_CHARSET_NOT_SUPPORTED: 0x040d,
  CLIENT_ERROR_CONFLICTING_ATTRIBUTES: 0x040e,
  CLIENT_ERROR_COMPRESSION_NOT_SUPPORTED: 0x040f,
  CLIENT_ERROR_COMPRESSION_ERROR: 0x0410,
  CLIENT_ERROR_DOCUMENT_FORMAT_ERROR: 0x0411,
  CLIENT_ERROR_DOCUMENT_ACCESS_ERROR: 0x0412,
  // Server Error Status Codes
  SERVER_ERROR_INTERNAL_ERROR: 0x0500,
  SERVER_ERROR_OPERATION_NOT_SUPPORTED: 0x0501,
  SERVER_ERROR_SERVICE_UNAVAILABLE: 0x0502,
  SERVER_ERROR_VERSION_NOT_SUPPORTED: 0x0503,
  SERVER_ERROR_DEVICE_ERROR: 0x0504,
  SERVER_ERROR_TEMPORARY_ERROR: 0x0505,
  SERVER_ERROR_NOT_ACCEPTING_JOBS: 0x0506,
  SERVER_ERROR_BUSY: 0x0507,
  SERVER_ERROR_JOB_CANCELED: 0x0508,
  SERVER_ERROR_MULTIPLE_DOCUMENT_JOBS_NOT_SUPPORTED: 0x0509
};
exports.statusCodes = statusCodes;